apiVersion: v1
kind: Secret
metadata:
    name: ksops-test
type: Opaque
stringData:
    hello: ENC[AES256_GCM,data:z6C13j4=,iv:LfF9C2EW/Z7TyQwirLeDuAhpf1FDmp3NPY97zm0X6Xk=,tag:VjM2GdlcvgJ3ewaQF8gcGA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNlhyS0QvVnRqM3R1UzlF
            VGVaaWpUa0NYblBTV2tvWWVrZGMxSnZ3bUJFCnNsVVJpNVlKczZTVS9sQlgxVmRi
            cTBQL0YwOVhiYXhIMTJCSW0rdm8rVFkKLS0tIENzSjIwMUNSUkE1WXRzeFVOY0lG
            cmoyYWJCM294RFNKbE5CQm54MVNFYmcKgCSmWUb8ZYG9p6tBFyWmtg3EpzeRJFHV
            3JKlMMLO5ejC10ZURMSKX6V3xz2hv986W5cQYldJO2sPD09PM3EjFg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mj9llmgzyevm6glaj8pdcc907t2kqnz4vl9juwtk3y5x59yeucvsvrrzxs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1S1pTM0NidGpPS2VsUXJQ
            ZHVRbWxZUjNBaHRLbUhEUXEvQmZ3bU1OaFY4CndCalBuWEhiQjRWcnhOWkU2YVRO
            Z2ZaMnF3eXVWMzVQZlo5dzNjWGV3bjgKLS0tIGVZZ2NQOGlIOWJlZU5sNEhwUWtw
            cGF6NkxDZGFFaVQrTVpPa0VQOGU4NnMK8qH1r8QQosm6HuDxTn/xtF0WaXThzmWg
            zCP2PX3eDzDTf2yG7kIGhM16/pg97D/zyVcE3S179IqIBYgfD2Ynug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1365my9m5sjp4gghlu40g8z5j8wx0r5pzd6a6gxfn69rex3mgy5lq3q80up
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T20:21:40Z"
    mac: ENC[AES256_GCM,data:cxNqRPvvICIZmQNA0JHEcP3bu96nNisp2uzMOH/+SV6tnm85NPv8ZMt5wPtTImVafbSOvduiOh9mSlEJNdZDtYTo/XSppXN5tPPvoEDLerQhGiOYqUW0xMhkMi8avB6zx+baGsDl2hyLYeFMjp/aPiaq4TDp8O0x6sqcypiSKpE=,iv:yIZi/7kUOyjGNRcDaGLqb1JkVslQ8wh//K8TR/ddgGA=,tag:hTKXupRKGoYxJakfPUKiZg==,type:str]
    version: 3.13.2
