AccountTag: ENC[AES256_GCM,data:972DQlBZ4wEJoCLntyK2gondiY/6fVWY6pw8w++jB+s=,iv:ULyGPuh7b8arq7qllDXXBtlU12Xm03cCROlX+uspa1Y=,tag:LxKWgiKlwoFn/vmLG+OGjg==,type:str]
TunnelID: ENC[AES256_GCM,data:myuxhXlpLp5VVWS6LjqhKL7Os8UzrWyv3UPicnBxJ9Zb3B3T,iv:KbbwpxP41ulDb2t3QyJULJhWNmuQD2vqkrOKNc29IPQ=,tag:kpAX+6J+0Z5G6BMRLKPumw==,type:str]
TunnelSecret: ENC[AES256_GCM,data:EKukTM0791/HImU8ugf/T6eaeEgc3HZYFoIKNsGTvbDOUMXL1nhgyTC0gfE=,iv:Wc5RgU8ouvWWY8dLqbiRjBJvVyBEwNnuuS3en63DpIE=,tag:vZ5QDuQXAXAU83Qx9qCoEQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNmNoeGRhK0JhUUk0SG1a
            OFhzMU5IV05RK2dtT3RESHpEVjhOeU1CTWw4CnkzRDZvVlBOSCs2YjQwSjUweGF2
            RXI5cVQ3eUZFajBHOUFzNExQV0NYanMKLS0tIENzbG5YY0ZZTHZKcWxKME5peno0
            c0pjcS9qaTR6bVpTQVB2WGVJb0lVVlUKjvwzV16HryYexaTJV40HQ8nZ++OZz1v+
            G8sIhAENfw6008ndWU4NDhkLU4GHM41ucMExxvmm10/GeJG+SMf0Lw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mj9llmgzyevm6glaj8pdcc907t2kqnz4vl9juwtk3y5x59yeucvsvrrzxs
    lastmodified: "2026-07-16T20:01:51Z"
    mac: ENC[AES256_GCM,data:+KguH75AHMkrQFcqL23ae8e7WO98NuhdFR3iCxZt3rZyycjKU7XCUuJ+9hmBiVib4AgnylCRxBdyNJvzvUjOerNvgu19WvCHmAQvakN1eDRzkWZBDAP5C+0X3rC5iiSvqHeyBKUoW3qAyb9N5sX3/NiSPYS/o9UjCDAZjn62ZRs=,iv:BAUsg31ly3pm2au0lriUWnQ6jRMu4w2X7wlL1hxaTXY=,tag:xS5NnKzI2uXi9PA8JWcE5A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
