AccountTag: ENC[AES256_GCM,data:HRhsJqFoYUqDnhl1edlzomhkj8pqQ/xsuzrNTc1kTpA=,iv:fuK9VEHSqtFtIt+mf3C4BcAyNF6l0cQ69iZGScHJVh4=,tag:8x3Gjzl0eKmx7b3oBEAHew==,type:str]
TunnelID: ENC[AES256_GCM,data:+b17ai07c87pJaM/433tTwrhGNZ/VACVWdiZ+ayco9sutSoT,iv:sO4zZnrMwLDUYdQTRpDQEJzLWwHqVubCHtMZ8fTbHEo=,tag:jAffF4RPKK8na3Nqf9psSg==,type:str]
TunnelSecret: ENC[AES256_GCM,data:Jfk1vkXcz0Q6t8oaW2bFzd0qaY6k6bELiBqhJd41DTEYIg7A2vPP1WAXt7k=,iv:hpvjx27dWTcc3uAYRYJ//sU2EpbsKCVRCETFoWYHwEU=,tag:vv4Pi6DcHqPTqAfIdz1KLw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNmNoeGRhK0JhUUk0SG1a
            OFhzMU5IV05RK2dtT3RESHpEVjhOeU1CTWw4CnkzRDZvVlBOSCs2YjQwSjUweGF2
            RXI5cVQ3eUZFajBHOUFzNExQV0NYanMKLS0tIENzbG5YY0ZZTHZKcWxKME5peno0
            c0pjcS9qaTR6bVpTQVB2WGVJb0lVVlUKjvwzV16HryYexaTJV40HQ8nZ++OZz1v+
            G8sIhAENfw6008ndWU4NDhkLU4GHM41ucMExxvmm10/GeJG+SMf0Lw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mj9llmgzyevm6glaj8pdcc907t2kqnz4vl9juwtk3y5x59yeucvsvrrzxs
    lastmodified: "2026-07-21T15:55:15Z"
    mac: ENC[AES256_GCM,data:OnXyA8ri+1ax8f+Lnz48OlNmQEdTjWJewLetFZqeC0JLu+A6ST3+j1WpC6wEIv2Jcd/FBJcpNOUJTnTQXUkhQu+0x7F1piFmdQgY2qUXFXRUAqkSJSEzDDqCblXtVSwNfNJdb/Ysa7/r1VyRgqEYYs1X9aZlQeV7r0bClESSUoA=,iv:m4WTfLJigdOfPqPzEF31kKA4VwwKsfQGWrTqP5pUG60=,tag:67xANldimJiIqNT1p+grHQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
