AccountTag: ENC[AES256_GCM,data:972DQlBZ4wEJoCLntyK2gondiY/6fVWY6pw8w++jB+s=,iv:ULyGPuh7b8arq7qllDXXBtlU12Xm03cCROlX+uspa1Y=,tag:LxKWgiKlwoFn/vmLG+OGjg==,type:str]
TunnelID: ENC[AES256_GCM,data:gpyhdjI4vzDBPbkbM8qctg0GwddMPnOVngFG0mNTCTQQ+aIB,iv:+LMOosH8UDSt5z5L3YbzbDHmc7JqJ5OL5V+oC+bihiY=,tag:ZzdqxFMTvsQvOLleBElRNw==,type:str]
TunnelSecret: ENC[AES256_GCM,data:/z/1yQkDhSJPqZIeyBfJd3dGW0VxHA2s9wxBwfKsK3Y6h/qRghtzeBmdDkM=,iv:cxw9I0+nVPhFVcA8mBXnRL5yjovIqQ4ttGuw31MbAGM=,tag:aUZnuDotM50QF6QuWqCKzg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNmNoeGRhK0JhUUk0SG1a
            OFhzMU5IV05RK2dtT3RESHpEVjhOeU1CTWw4CnkzRDZvVlBOSCs2YjQwSjUweGF2
            RXI5cVQ3eUZFajBHOUFzNExQV0NYanMKLS0tIENzbG5YY0ZZTHZKcWxKME5peno0
            c0pjcS9qaTR6bVpTQVB2WGVJb0lVVlUKjvwzV16HryYexaTJV40HQ8nZ++OZz1v+
            G8sIhAENfw6008ndWU4NDhkLU4GHM41ucMExxvmm10/GeJG+SMf0Lw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mj9llmgzyevm6glaj8pdcc907t2kqnz4vl9juwtk3y5x59yeucvsvrrzxs
    lastmodified: "2026-07-18T23:21:38Z"
    mac: ENC[AES256_GCM,data:O3Eb2COCuwvW8EQBzpN8vqx4PWwtE3P3GaLXW8nAGq7CwewJk4j8jCje2M3ErfO+2LAxs20xWH4/+A1dtn824Eu3y8Wy4wb2BME9CYQT18yx3pkUxOGG2h/xdKVZajvV/4NliaDVdZ5Am7rntVdM50YhDfaQAkS7FV4n0h3olgs=,iv:iR3B9lz65CB4D7cZoDeTQoyo5iL71FgBgKLefgOoJv8=,tag:WRteQ8t6pqjcG8e0AIDgQQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
